
export GOPATH=$HOME/go
export GOBIN=$GOPATH/bin
export PATH=$GOPATH/bin:$GOROOT/bin:$PATH

if [[ -f /opt/homebrew/bin/brew ]]; then
  export HOMEBREW_PREFIX=/opt/homebrew
elif [[ -f /home/linuxbrew/.linuxbrew/bin/brew ]]; then
  export HOMEBREW_PREFIX=/home/linuxbrew/.linuxbrew
fi

# gcloud binaries
export PATH=$HOMEBREW_PREFIX/share/google-cloud-sdk/bin:$PATH


autoload -Uz compinit && compinit

# load nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$HOMEBREW_PREFIX/opt/nvm/nvm.sh" ] && \. "$HOMEBREW_PREFIX/opt/nvm/nvm.sh"  # This loads nvm
[ -s "$HOMEBREW_PREFIX/opt/nvm/etc/bash_completion.d/nvm" ] && \. "$HOMEBREW_PREFIX/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

# export USE_GKE_GCLOUD_AUTH_PLUGIN=True

export CLOUDSDK_PYTHON=$HOMEBREW_PREFIX/bin/python3
# export GOPRIVATE=

alias docker_start='colima start --profile default --activate --arch aarch64 --cpu 10 --disk 48 --memory 8 --mount ${HOME}:w --mount-inotify --ssh-agent --vm-type vz --vz-rosetta -v'
alias docker_prune='docker image prune -a -f'
alias docker_prune_hard='docker system prune -a --volumes -f'

load-nvmrc() {
  local node_version="$(nvm version)"
  local nvmrc_path="$(nvm_find_nvmrc)"

  if [ -n "$nvmrc_path" ]; then
    local nvmrc_node_version=$(nvm version "$(cat "${nvmrc_path}")")

    if [ "$nvmrc_node_version" = "N/A" ]; then
      nvm install
    elif [ "$nvmrc_node_version" != "$node_version" ]; then
      nvm use
    fi
  elif [ "$node_version" != "$(nvm version default)" ]; then
    echo "Reverting to nvm default version"
    nvm use default
  fi
}

function sort_json() {
  jq 'def sort_arrays:
      . as $in |
      if type == "array" then
          map(sort_arrays) | sort
      elif type == "object" then
          with_entries(.value |= sort_arrays)
      else
          .
      end;
  sort_arrays'
}

load-nvmrc

# gcloud completion
[ -s "$HOMEBREW_PREFIX/share/google-cloud-sdk/completion.zsh.inc" ] && \. "$HOMEBREW_PREFIX/share/google-cloud-sdk/completion.zsh.inc"

# kubectl completion
source <(kubectl completion zsh)
export PATH="/usr/local/sbin:$PATH"
export PATH="/usr/local/bin:$PATH"
export PATH="$HOME/bin:$PATH"

if [[ "$(uname)" == "Darwin" ]]; then
  export COLIMA_VM="default"
  export COLIMA_VM_SOCKET="${HOME}/.colima/${COLIMA_VM}/docker.sock"
  export DOCKER_HOST="unix://${COLIMA_VM_SOCKET}"
fi

autoload -Uz colors && colors

# Colorized command output
if [[ "$(uname)" == "Darwin" ]]; then
  export CLICOLOR=1
  export LSCOLORS="ExGxFxdxCxDxDxhbadExEx"
  alias ls='ls -G'
else
  export LS_COLORS="rs=0:di=01;34:ln=01;36:ex=01;32:*.tar=01;31:*.zip=01;31"
  alias ls='ls --color=auto'
fi
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# Colored man pages (less)
export LESS_TERMCAP_mb=$'\e[1;32m'
export LESS_TERMCAP_md=$'\e[1;32m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[01;33m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[1;4;31m'

autoload -Uz vcs_info
zstyle ':vcs_info:*' enable git
zstyle ':vcs_info:git:*' check-for-changes true
zstyle ':vcs_info:git:*' unstagedstr '*'
zstyle ':vcs_info:git:*' stagedstr '+'
zstyle ':vcs_info:git:*' formats ' %F{green}(%b%u%c)%f'
zstyle ':vcs_info:git:*' actionformats ' %F{green}(%b|%a%u%c)%f'

set_prompt() {
  local dt="%D{%d/%m/%y %H:%M:%S}"
  local userhost="%n@%m"
  local cwd="%~"
  local sym="%#"

  vcs_info

  # Add virtual environment indicator
  local venv_indicator=""
  if [[ -n "$VIRTUAL_ENV" ]]; then
    venv_indicator=" %F{cyan}($(basename $VIRTUAL_ENV))%f"
  fi

  PROMPT="%F{blue}[$dt]%f %F{magenta}${userhost}%f %F{yellow}${cwd}%f${vcs_info_msg_0_}${venv_indicator}
%B${sym}%b "
  RPROMPT=""  # keep right prompt empty like your original
}

autoload -Uz add-zsh-hook
add-zsh-hook precmd set_prompt
set_prompt   # set immediately for the first prompt

# basictex
[[ -d /usr/local/texlive/2026basic/bin/universal-darwin ]] && export PATH="/usr/local/texlive/2026basic/bin/universal-darwin:$PATH"

[[ -f ~/.aliases.personal ]] && source ~/.aliases.personal
[[ -f ~/.aliases.work ]] && source ~/.aliases.work

[ -s "$HOMEBREW_PREFIX/share/zsh-autosuggestions/zsh-autosuggestions.zsh" ] && \. "$HOMEBREW_PREFIX/share/zsh-autosuggestions/zsh-autosuggestions.zsh"
[ -s "$HOMEBREW_PREFIX/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" ] && \. "$HOMEBREW_PREFIX/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
# [!NOTE] If you receive the “highlighters directory not found” error message, you may need to add the following to your ~/.zshenv:
# export ZSH_HIGHLIGHT_HIGHLIGHTERS_DIR=$HOMEBREW_PREFIX/share/zsh-syntax-highlighting/highlighters

# # keep at the end of the file
eval "$(direnv hook zsh)"
# keep at the end of the file
eval "$(starship init zsh)"

export PATH="$HOME/.local/bin:$HOME/.local/bin/personal:$HOME/.local/bin/work:$PATH"
export PATH="$HOMEBREW_PREFIX/opt/libpq/bin:$PATH"
